-- MySQL Script generated by MySQL Workbench
-- Tue Jun  7 23:59:28 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`customer` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`customer` (
  `cus_id` INT UNSIGNED NOT NULL COMMENT '',
  `cus_fname` VARCHAR(20) NOT NULL COMMENT '',
  `cus_lname` VARCHAR(20) NOT NULL COMMENT '',
  `cus_street` VARCHAR(30) NOT NULL COMMENT '',
  `cus_city` VARCHAR(20) NOT NULL COMMENT '',
  `cus_state` CHAR(2) NOT NULL COMMENT '',
  `cus_zip` INT NOT NULL COMMENT '',
  `cus_phone` BIGINT NOT NULL COMMENT '',
  `cus_email` VARCHAR(45) NOT NULL COMMENT '',
  `cus_balance` DECIMAL(6,2) NOT NULL COMMENT '',
  `cus_totalsales` DECIMAL(6,2) NOT NULL COMMENT '',
  `cus_notes` VARCHAR(100) NOT NULL COMMENT '',
  PRIMARY KEY (`cus_id`)  COMMENT '')
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`store`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`store` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`store` (
  `sto_id` INT UNSIGNED NOT NULL COMMENT '',
  `sto_name` VARCHAR(20) NOT NULL COMMENT '',
  `sto_street` VARCHAR(30) NOT NULL COMMENT '',
  `sto_city` VARCHAR(20) NOT NULL COMMENT '',
  `sto_zip` INT NOT NULL COMMENT '',
  `sto_phone` BIGINT NOT NULL COMMENT '',
  `sto_email` VARCHAR(45) NOT NULL COMMENT '',
  `sto_std_sales` INT NOT NULL COMMENT '',
  `sto_url` VARCHAR(45) NOT NULL COMMENT '',
  `sto_notes` VARCHAR(100) NOT NULL COMMENT '',
  PRIMARY KEY (`sto_id`)  COMMENT '')
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`pet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pet` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`pet` (
  `pet_id` INT UNSIGNED NOT NULL COMMENT '',
  `sto_id` INT UNSIGNED NOT NULL COMMENT '',
  `cus_id` INT UNSIGNED NULL COMMENT '',
  `pet_type` VARCHAR(45) NOT NULL COMMENT '',
  `pet_sex` ENUM('M', 'F') NOT NULL COMMENT '',
  `pet_price` INT NOT NULL COMMENT '',
  `pet_age` INT NOT NULL COMMENT '',
  `pet_color` CHAR(15) NOT NULL COMMENT '',
  `pet_sale_date` DATE NOT NULL COMMENT '',
  `pet_vaccine` ENUM('Y', 'N') NOT NULL COMMENT '',
  `pet_neuter` ENUM('Y', 'N') NOT NULL COMMENT '',
  `pet_notes` VARCHAR(100) NOT NULL COMMENT '',
  PRIMARY KEY (`pet_id`)  COMMENT '',
  INDEX `fk_pet_customer_idx` (`cus_id` ASC)  COMMENT '',
  INDEX `fk_pet_store1_idx` (`sto_id` ASC)  COMMENT '',
  CONSTRAINT `fk_pet_customer`
    FOREIGN KEY (`cus_id`)
    REFERENCES `mydb`.`customer` (`cus_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pet_store1`
    FOREIGN KEY (`sto_id`)
    REFERENCES `mydb`.`store` (`sto_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
