# This is Lucas's .bash_profile

export LC_PORTFOLIO_DIR=~/Desktop/LucasProjects/LucasCosta_portfolio

# Aliases:
alias ls='eza --long --header --git -TL 1' # must download exa first
alias la='ls -la'
alias cpwd="pwd | tr -d '\n' | pbcopy" # copying pwd co clipboard
alias c="cd $LC_PORTFOLIO_DIR"

# Git Aliases
alias ga='git add .; git status'
alias gs='git status'
alias gcm='git commit -m'
alias gp='git push'
alias gc='git checkout'
# This checks all branches not merged with origin, other than master, develop and staging, then deletes them from local
alias gclean='echo "Doing a git pull, git fetch --all --prune and a gclean" && git pull && git fetch --all --prune && git branch --merged | grep -v "\*" | grep -Ev "(\*|master|develop|staging|dev)" | xargs -n 1 git branch -d'
# Possible new gclean? git branch -vv | awk '/: gone]/{print $1}' | xargs git branch -d
alias gcb='git checkout -b' # add branchName to be created/checked out after

# Scripts
alias atomInstall="$LC_PORTFOLIO_DIR/.dotfiles/scripts/install-atom-packages.sh"
alias atomGetPackages="$LC_PORTFOLIO_DIR/.dotfiles/scripts/get-atom-packages.sh"
alias gcall="$LC_PORTFOLIO_DIR/.dotfiles/scripts/git-checkout-master-all.sh"
alias display-placer="$LC_PORTFOLIO_DIR/.dotfiles/scripts/display-placer.sh"

# Homebrew
eval "$(/opt/homebrew/bin/brew shellenv)"
# Pyenv
eval "$(pyenv init --path)"

# Exports:
export NVM_DIR="$HOME/.nvm"
  [ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"  # This loads nvm
  [ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion

#. "$HOME/.local/bin/env"

if [ -f ~/.bash_profile_work ]; then
  source ~/.bash_profile_work
fi
