# This is Lucas's .bash_profile

export LC_PORTFOLIO_DIR=~/Desktop/LucasProjects/LucasCosta_portfolio

# Aliases:
alias ls='eza --long --header --git' # must download exa first
alias la='ls -la'
alias cpwd="pwd | tr -d '\n' | pbcopy" # copying pwd co clipboard
alias c="cd $LC_PORTFOLIO_DIR"

# Git Aliases
alias ga='git add .; git status'
alias gs='git status'
alias gcm='git commit -m'
alias gp='git push'
alias gc='git checkout'
alias gcb='git checkout -b' # add branchName to be created/checked out after

# This checks all branches not merged with origin, other than master, develop and staging, then deletes them from local
#alias gclean='echo "Doing a git pull, git fetch --all --prune and a gclean" && git pull && git fetch --all --prune && git branch --merged | grep -v "\*" | grep -Ev "(\*|master|develop|staging|dev)" | xargs -n 1 git branch -d'
alias gclean='git pull && git fetch --all --prune && (git branch -vv | grep ": gone]" | grep -Ev "(master|develop|staging|dev|main)" | awk "{print \$1}" | xargs git branch -D || echo "No stale branches to clean up")'


# Scripts
alias atomInstall="$LC_PORTFOLIO_DIR/.dotfiles/scripts/install-atom-packages.sh"
alias atomGetPackages="$LC_PORTFOLIO_DIR/.dotfiles/scripts/get-atom-packages.sh"
alias gcall="$LC_PORTFOLIO_DIR/.dotfiles/scripts/git-checkout-master-all.sh"
alias display-placer="$LC_PORTFOLIO_DIR/.dotfiles/scripts/display-placer.sh"

# Homebrew
eval "$(/opt/homebrew/bin/brew shellenv)"
# Pyenv
# eval "$(pyenv init --path)"

# Exports:
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion


if [ -f ~/.bash_profile_work ]; then
  source ~/.bash_profile_work
fi
