# This is Lucas's .bash_profile, last updated on October, 2018

# Aliases:
alias ls='exa --long --header --git -TL 1' # must download exa first
alias la='ls -la'
alias cpwd="pwd | tr -d '\n' | pbcopy" # copying pwd co clipboard
alias c='cd ~/Desktop/LucasCosta_portfolio'

# Git Aliases
alias ga='git add .; git status'
alias gs='git status'
alias gcm='git commit -m'
alias gp='git push'
alias gc='git checkout'
# This checks all branches not merged with origin, other than master, develop and staging, then deletes them from local
alias gclean='git branch --merged | grep -v "\*" | grep -Ev "(\*|master|develop|staging)" | xargs -n 1 git branch -d'
alias gcb='git checkout -b' # add branchName to be created/checked out after
# alias gpull='git pull'
# alias gph='git push origin HEAD'
# alias gpo='git push origin'

# Exports:
export PATH=$PATH:/usr/local/sbin
export PATH=$PATH:/Users/$USER/Library/Python/2.7/bin
export PATH=$PATH:/Users/$USER/Library/Python/3.7/bin
export PATH=$PATH:/Applications/Postgres.app/Contents/Versions/11/bin/
export PATH=$PATH:/usr/bin/java
export PATH="$PATH:`yarn global bin`"

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/Users/$USER/.sdkman"
[[ -s "/Users/$USER/.sdkman/bin/sdkman-init.sh" ]] && source "/Users/$USER/.sdkman/bin/sdkman-init.sh"
